name: Static code analysis

on: [ pull_request ]

jobs:
  analysis:
    name: static code analysis
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
          - "8.3"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pcntl, sync
          coverage: none
        env:
          fail-fast: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Composer install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "highest"
          composer-options: "--optimize-autoloader"

      - name: 'phpcs'
        run: vendor/bin/phpcs

      - name: 'psalm'
        run: vendor/bin/psalm --stats --output-format=github
